layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 16
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  hackerrank: j_j_suder
  # instagram: your_username
  linkedin: john-suder-5ba5066
  # stackoverflow: your_user_id
  # twitter: your_username
  # youtube: your_username

topics:
  - name: Compiler
    web_url: https://github.com/topics/compiler

  - name: OCaml
    web_url: https://github.com/topics/ocaml
    image_url: https://raw.githubusercontent.com/github/explore/f5a57d438b9deec8a209ade5fea3977349ffa2db/topics/ocaml/ocaml.png

  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png
